### ISSUE TITLE
[BUG] Getting stuck on loading screen after zoning into interiors

### ISSUE THREAD

**Issue by LEMONER123** [CalderCob/EOA-bug-tracker#219] opened 2023-12-06 01:35 UTC
### Description of the issue

In and out of the room, during the loading process, the card progress bar appears, you must exit the game, enter again to recover

### Where it Happens

Most of the rooms in Bray, especially those of the Sage skills trainer,

**Comment by echoes-emu** [comment] 2023-12-08 00:45
Duplicate of #212

**Closed by echoes-emu** 2023-12-08 00:45 UTC
Labels: bug
