### ISSUE TITLE
[BUG] Hobbit burglar broken animation with stutter

### ISSUE THREAD

**Issue by Lighwan** [CalderCob/EOA-bug-tracker#90] opened 2023-09-13 18:33 UTC
Slash animation on hobbit burglars has a stutter after using it, which delays skills by 1 second. Getting the correct animation can speed up your skill use and increase your dps by like 25%. Super RNG based

hobbit burg wielding two swords

video of animation (note the stutter after each swing)
https://github.com/CalderCob/EOA-bug-tracker/assets/68567124/40cfd835-e4e3-4ecc-b90b-7602fc622c78

if i were to use a skill after the swing the stutter would cause a delay

**Comment by Lighwan** [comment] 2023-09-13 18:37
died ingame while writing this so u better fix

**Comment by echoes-emu** [comment] 2023-09-13 19:53
Duplicate of #55
Animation are client data  so unlikely this will be fixed

**Closed by echoes-emu** 2023-09-13 19:53 UTC
Labels: bug
