### ISSUE TITLE
The skills of a hunter and a bard[SKILL]

### ISSUE THREAD

**Issue by LEMONER123** [CalderCob/EOA-bug-tracker#221] opened 2023-12-06 01:41 UTC
### Skill Name

Hunter's stance and Bard's Aura ability, after entering and leaving the room, the actual effect is lost, but the skills bar still shows activation

**Comment by echoes-emu** [comment] 2023-12-06 23:59
Duplicate of #213

**Closed by echoes-emu** 2023-12-06 23:59 UTC
Labels: quest, skill
